FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y default-jdk maven git jq curl unzip python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# [DBMS_INSTALL_HERE]

COPY entrypoint.sh /root/entrypoint.sh
COPY config.json /root/config.json

WORKDIR /root
RUN mkdir -p /root/sqlancer

RUN chmod +x /root/entrypoint.sh
CMD ["/root/entrypoint.sh"]
